### ISSUE TITLE
Update Total Chaos to 1.40

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/com.moddb.TotalChaos#13]
https://www.moddb.com/mods/total-chaos/downloads/total-chaos-directors-cut-140

This will hopefully allow (and probably require) updating GZDoom to a newer version.

**TODO:** Contact @barthalion about downloading the new version archive and hosting it on dl.flathub.org.

**Comment by barthalion** [comment]
Did you check if it's going to work yet?

**Comment by AsciiWolf** [comment]
Not yet, but it should work fine (it works fine with newer GZDoom on Windows).

**Comment by AsciiWolf** [comment]
It looks like the official Windows version of Total Chaos 1.40 is using GZDoom 4.8.2 (from 2022-07-04) with Vulkan renderer.

**Comment by barthalion** [comment]
I have uploaded `totalchaos_dc_b5.zip` to the same location as before.

**Comment by AsciiWolf** [comment]
Thanks! I will try preparing the update in upcoming weeks. :-)
