### ISSUE TITLE
error: syntax error, unexpected NEW_IDENTIFIER

### ISSUE THREAD

**Issue by pxsxs** [flathub/com.moddb.TotalChaos#8]
I get de following error when try to open Total Chaos

```
Compile Shader 'shaders/glsl/shadowmap.fp':
0:23(29): error: syntax error, unexpected NEW_IDENTIFIER
```

**Comment by AsciiWolf** [comment]
Hmm, that's strange. What is your OS, GPU drivers version and HW configuration?

**Comment by pxsxs** [comment]
this is the neofetch output:

OS: Debian GNU/Linux bullseye/sid x86_64 
Host: HP Pavilion dm4 Notebook PC 0792100000204610000620100 
Kernel: 5.10.0-5-amd64 
Uptime: 8 hours, 58 mins 
Packages: 3232 (dpkg), 7 (flatpak) 
Shell: bash 5.1.4 
Resolution: 1366x768 
WM: i3 
Theme: Adwaita-dark [GTK2/3] 
Icons: hicolor [GTK2/3] 
Terminal: xfce4-terminal 
Terminal Font: Monospace 12 
CPU: Intel i5-3210M (4) @ 3.100GHz 
GPU: Intel 3rd Gen Core processor Graphics Controller 
Memory: 1670MiB / 7858MiB

**Comment by AsciiWolf** [comment]
I just tested it on my ThinkPad with Intel GPU and the game works fine. You seem to have some problem with shader compiler. Do other OpenGL/Vulkan games work for you?

**Comment by pxsxs** [comment]
I just tested the game and now it works... weird, and yes, other games with opengl work fine.
